### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by bytestream**

### CODE REVIEW

**Comment by ralflang** [comment]
While I am OK with this, I have not had time to actually test this version against php 8 yet.
BTW you would want to edit the version constraint in the .horde.yml file as the composer.json file gets autogenerated from there.

I see some tests failing - this may be unrelated. I will approve nevertheless.

**Comment by bytestream** [comment]
@ralflang hold up :D

I'll submit PRs to all repositories related to `horde/imap_client` which are currently missing PHP 8 support. Please wait until the workflow is green though...

Is there any reason you're testing against PHPUnit 9.0 and 9.5? Why not just 9.5?

**Comment by ralflang** [comment]
There was a reason but it's no longer relevant. PHPUnit marks some classes as no bc/internal and Horde_Test does (or used to do) some funny things with these. I could more easily discern if a test failed due to this or due to bad conversion by Marco and me. Later on it was just copy/paste without much thought.

**Comment by bytestream** [comment]
OK thanks @ralflang

I've sent PRs to the relevant repositories. The following should be possible to merge in the order listed below:
1. https://github.com/maintaina-com/Stream_Filter/pull/3
2. https://github.com/maintaina-com/Idna/pull/2
3. https://github.com/maintaina-com/Stream/pull/2
4. https://github.com/maintaina-com/Support/pull/2
5. https://github.com/maintaina-com/Text_Flowed/pull/2
6. https://github.com/maintaina-com/Socket_Client/pull/1
7. https://github.com/maintaina-com/Crypt_Blowfish/pull/2
8. https://github.com/maintaina-com/Secret/pull/2 

These three will fail CI as they depend on each other... 
* https://github.com/maintaina-com/ListHeaders/pull/2
* https://github.com/maintaina-com/Mime/pull/2
* https://github.com/maintaina-com/Mail/pull/2

Once all are merged `horde/imap_client` should work on PHP 8

**Pull request merged**
